services:
  mongo:
    image: mongo:8
    container_name: verys-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  verys:
    build:
      context: .
      args:
        ENV: dev
    container_name: verys-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: verys
      USERNAME_SMTP: ${USERNAME_SMTP}
      PASSWORD_SMTP: ${PASSWORD_SMTP}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      OPENOBSERVE_ENDPOINT: ${OPENOBSERVE_ENDPOINT}
      OPENOBSERVE_USER: ${OPENOBSERVE_USER}
      OPENOBSERVE_TOKEN: ${OPENOBSERVE_TOKEN}
      VERYS_CLIENT_ID: ${VERYS_CLIENT_ID}
      VERYS_CLIENT_REDIRECT_URI: ${VERYS_CLIENT_REDIRECT_URI}
      VERYS_CLIENT_REGISTRATION_URI: ${VERYS_CLIENT_REGISTRATION_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      MICROSOFT_TENANT: ${MICROSOFT_TENANT:-common}
volumes:
  mongodata:
